services:
  reverse-proxy:
    build:
      context: ./reverse-proxy
    ports:
      - "80:80"  
    volumes:
      - ./logs:/var/log/nginx 
    depends_on:
      - web-app

  web-app:
    build:
      context: ./web-app
    ports:
      - "5000:5000"   
    environment:
      - NODE_ENV=production
    # expose:
    #   - "5000"  
